### ISSUE TITLE
SSL Labs API Invocations Require User-Agent

### ISSUE THREAD

**Issue by BadgerBadgerBadgerBadger** [keithws/node-ssllabs#3]
Hi, in our usage of the node-ssllabs module we noticed that calls to the SSLLabs API were no longer working. We twiddled around a bit and saw that adding a user-agent made everything go back to normal. Wanted to let you know.

**Comment by keithws** [comment]
Good to know! I will add a default user agent string.

**Comment by keithws** [comment]
Well, I'm going to add a default user agent string because it’s the right thing to do, however, I am still able to run my test suite and test 8 different domains without a user agent string.

I've noticed the SSL Labs API has become less stable since December 2019. Perhaps, it was coincidence? Can you share more details?

**Comment by BadgerBadgerBadgerBadger** [comment]
Hi. I don't have the logs I wish I had, but we were getting errors from SSL labs, (with a status code of 500), for a solid 24 hours. We tried manually calling the endpoint and it looks like that worked fine when a user-agent was added and failed with a 500 when one was not included.

But I tried both the npm module and direct HTTP calls, and looks like it was indeed a temporary problem. Maybe something on SSLlab's end leading to a false positive.

Consider the matter closed and sorry for bugging you.

**Comment by BadgerBadgerBadgerBadger** [comment]
Okay, I was able to replicate the issue. Could you have a look at: https://runkit.com/badgerbadgerbadgerbadger/5e8d90f4261e68001a30afa0 ?

I'm seeing a `status` of `READY` but under `endpoints`statusMessage` is `Internal Error`. It's all a bit too magical and I have no idea what's going on.

**Comment by tomyam1** [comment]
Got the same issue (Internal Error status message)
Adding a user agent fixed it

**Comment by keithws** [comment]
I added a User Agent header in v1.1.3 and v2.0.0.

Note, v1.1.13 build failed on node 6 because `eslint` and `nyc` no longer support it. So, I created v2.0.0 that removes the build test on node 6.

Note, v2.0.0 builds failed due to IPv6 network connection failures on some of the hosts in my test suite.

I'll give them some time to correct that network issues and do another build.
